// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebQQRobot.DataModel
{

    public partial class QQGroupList
    {
        public class Result2
        {

            [JsonProperty("gmasklist")]
            public object[] Gmasklist;

            [JsonProperty("gnamelist")]
            public Gnamelist2[] Gnamelist;

            [JsonProperty("gmarklist")]
            public object[] Gmarklist;
        }
    }

}
