// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebQQRobot.DataModel
{

    public partial class QQGroupMemberList
    {
        public class Vipinfo2
        {

            [JsonProperty("vip_level")]
            public int VipLevel;

            [JsonProperty("u")]
            public object U;

            [JsonProperty("is_vip")]
            public int IsVip;
        }
    }

}
