// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebQQRobot.DataModel
{

    public partial class QQMemberList
    {
        public class Minfo2
        {

            [JsonProperty("nick")]
            public string Nick;

            [JsonProperty("province")]
            public string Province;

            [JsonProperty("gender")]
            public string Gender;

            [JsonProperty("uin")]
            public object Uin;

            [JsonProperty("country")]
            public string Country;

            [JsonProperty("city")]
            public string City;
        }
    }

}
