// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebQQRobot.DataModel
{

    public partial class QQMessage
    {
        public class Result2
        {

            [JsonProperty("poll_type")]
            public string PollType;

            [JsonProperty("value")]
            public Value2 Value;
        }
    }

}
