// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebQQRobot.DataModel
{

    public partial class QQMessage
    {
        public class Value2
        {

            [JsonProperty("msg_id")]
            public int MsgId;

            [JsonProperty("from_uin")]
            public object FromUin;

            [JsonProperty("to_uin")]
            public int ToUin;

            [JsonProperty("msg_id2")]
            public int MsgId2;

            [JsonProperty("msg_type")]
            public int MsgType;

            [JsonProperty("reply_ip")]
            public int ReplyIp;

            [JsonProperty("group_code")]
            public long GroupCode;

            [JsonProperty("send_uin")]
            public object SendUin;

            [JsonProperty("seq")]
            public int Seq;

            [JsonProperty("time")]
            public int Time;

            [JsonProperty("info_seq")]
            public int InfoSeq;

            [JsonProperty("content")]
            public object[] Content;
        }
    }

}
