// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebQQRobot.DataModel
{

    public partial class QQMemberList
    {
        public class Member
        {

            [JsonProperty("muin")]
            public object Muin;

            [JsonProperty("mflag")]
            public int Mflag;
        }
    }

}
