// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebQQRobot.DataModel
{

    public partial class QQGroupMemberList
    {
        public class Ginfo2
        {

            [JsonProperty("face")]
            public int Face;

            [JsonProperty("memo")]
            public string Memo;

            [JsonProperty("class")]
            public int Class;

            [JsonProperty("fingermemo")]
            public string Fingermemo;

            [JsonProperty("code")]
            public int Code;

            [JsonProperty("createtime")]
            public int Createtime;

            [JsonProperty("flag")]
            public int Flag;

            [JsonProperty("level")]
            public int Level;

            [JsonProperty("name")]
            public string Name;

            [JsonProperty("gid")]
            public int Gid;

            [JsonProperty("owner")]
            public int Owner;

            [JsonProperty("members")]
            public Member[] Members;

            [JsonProperty("option")]
            public int Option;
        }
    }

}
