// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebQQRobot.DataModel
{

    public partial class QQGroupList
    {
        public class Gnamelist2
        {

            [JsonProperty("flag")]
            public int Flag;

            [JsonProperty("name")]
            public string Name;

            [JsonProperty("gid")]
            public long Gid;

            [JsonProperty("code")]
            public object Code;
        }
    }

}
